paths:
  base-image:
    jvm-17: registry.access.redhat.com/ubi8/openjdk-17:1.11
  dockerfile:
    jvm-17: src/main/docker/Dockerfile.jvm17

quarkus:
  application:
    name: rest-heroes
quarkus:
  kubernetes-client:
    trust-certs: true
  log:
    level: INFO
    category:
      "io.quarkus.sample.superheroes":
        level: DEBUG
    console:
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"
      level: INFO
      darken: 1
  opentelemetry:
    tracer:
      resource-attributes: "app=${quarkus.application.name},application=heroes-service,system=quarkus-super-heroes"
      exporter:
        otlp:
          endpoint: http://localhost:4317
  hibernate-orm:
    database:
      generation: drop-and-create
  http:
    cors: true
    port: 8083
    test-port: 0
  jackson:
    serialization-inclusion: non-empty
  smallrye-openapi:
    info-title: Hero API
    info-description: This API allows CRUD operations on a hero
    info-version: 1.0
    info-contact-name: Quarkus
    info-contact-url: https://github.com/quarkusio
    servers: "http://localhost:${quarkus.http.port}"
  swagger-ui:
    always-include: true
  container-image:
    builder: docker
    registry: quay.io
    group: quarkus-super-heroes
    name: "${quarkus.application.name}"
  kubernetes:
    part-of: heroes-service
    annotations:
      "app.openshift.io/connects-to": heroes-db,otel-collector
    env:
      configmaps: "${quarkus.application.name}-config"
      secrets: "${quarkus.application.name}-config-creds"
    labels:
      app: "${quarkus.application.name}"
      application: "${quarkus.kubernetes.part-of}"
      system: quarkus-super-heroes
  openshift:
    part-of: "${quarkus.kubernetes.part-of}"
    route:
      expose: true
    annotations:
      "app.openshift.io/connects-to": heroes-db,otel-collector
    env:
      configmaps: "${quarkus.kubernetes.env.configmaps}"
      secrets: "${quarkus.kubernetes.env.secrets}"
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.openshift.part-of}"
      system: "${quarkus.kubernetes.labels.system}"
  knative:
    part-of: "${quarkus.kubernetes.part-of}"
    annotations:
      "app.openshift.io/connects-to": heroes-db,otel-collector
    env:
      configmaps: "${quarkus.kubernetes.env.configmaps}"
      secrets: "${quarkus.kubernetes.env.secrets}"
    labels:
      app: "${quarkus.kubernetes.labels.app}"
      application: "${quarkus.openshift.part-of}"
      system: "${quarkus.kubernetes.labels.system}"

"%dev":
  quarkus:
    log:
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        level: DEBUG

"%test":
  quarkus:
    log:
      console:
        format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"
        level: DEBUG

"%prod":
  quarkus:
    hibernate-orm:
      sql-load-script: import.sql

"%kubernetes":
  quarkus:
    config:
      profile:
        parent: prod

"%kubernetes-17":
  quarkus:
    config:
      profile:
        parent: prod
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-17}"

"%openshift":
  quarkus:
    config:
      profile:
        parent: prod
    container-image:
      builder: openshift
    kubernetes:
      deployment-target: openshift

"%openshift-17":
  quarkus:
    config:
      profile:
        parent: prod
    container-image:
      builder: openshift
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-17}"
    kubernetes:
      deployment-target: openshift
    openshift:
      jvm-dockerfile: "${paths.dockerfile.jvm-17}"
      base-jvm-image: "${paths.base-image.jvm-17}"

"%knative":
  quarkus:
    config:
      profile:
        parent: prod
    kubernetes:
      deployment-target: knative

"%knative-17":
  quarkus:
    config:
      profile:
        parent: prod
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-17}"
    kubernetes:
      deployment-target: knative

"%knative-openshift":
  quarkus:
    config:
      profile:
        parent: prod
    container-image:
      builder: openshift
    kubernetes:
      deployment-target: knative

"%knative-openshift-17":
  quarkus:
    config:
      profile:
        parent: prod
    container-image:
      builder: openshift
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-17}"
    kubernetes:
      deployment-target: knative
    openshift:
      jvm-dockerfile: "${paths.dockerfile.jvm-17}"
      base-jvm-image: "${paths.base-image.jvm-17}"

"%minikube":
  quarkus:
    config:
      profile:
        parent: prod
    kubernetes:
      deployment-target: minikube

"%minikube-17":
  quarkus:
    config:
      profile:
        parent: prod
    docker:
      dockerfile-jvm-path: "${paths.dockerfile.jvm-17}"
    kubernetes:
      deployment-target: minikube
