apiVersion: v1
kind: Secret
metadata:
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
  name: rest-villains-config-creds
type: Opaque
stringData:
  quarkus.datasource.password: superbad
  quarkus.datasource.username: superbad
