apiVersion: v1
metadata:
  labels:
    app: rest-villains
    application: villains-service
    system: quarkus-super-heroes
  name: rest-villains-config
data:
  quarkus.datasource.jdbc.url: jdbc:otel:postgresql://villains-db:5432/villains_database
  quarkus.hibernate-orm.database.generation: validate
  quarkus.hibernate-orm.sql-load-script: no-file
  quarkus.opentelemetry.tracer.exporter.otlp.endpoint: http://otel-collector:4317
kind: ConfigMap
